# frozen_string_literal: true

Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
Campaign.create(name: 'The GoCarShare Team',
                image: 'Image',
                percent_raised: 20,
                amount_raised: 20,
                target_amount: 2000,
                sector: 'Automotive',
                country: 'UK',
                invest_multiple: 5)
